SElECT C.COMPANY_CODE,C.FOUNDER,
COUNT(DISTINCT LM.LEAD_MANAGER_CODE),
COUNT(DISTINCT SM.SENIOR_MANAGER_CODE),
COUNT(DISTINCT M.MANAGER_CODE),
COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY C 
INNER JOIN Lead_Manager LM ON C.COMPANY_CODE = LM.COMPANY_CODE
INNER JOIN Senior_Manager SM USING(LEAD_MANAGER_CODE)
INNER JOIN Manager M USING(Senior_Manager_CODE)
INNER JOIN Employee E USING(MANAGER_CODE)
GROUP BY C.COMPANY_CODE,C.FOUNDER
ORDER BY C.COMPANY_CODE;
