SELECT CASE 
WHEN A+B<=C OR A+C<=B OR B+C<=A THEN 'Not A Triangle'
WHEN A=B AND A=C AND C= B THEN 'Equilateral'
WHEN A=B OR A=C OR C= B THEN 'Isosceles'
WHEN A!=B AND A!=C AND C!= B THEN 'Scalene'
END
FROM TRIANGLES;
